FROM node:22-alpine AS react-build

WORKDIR /app

EXPOSE 5173

COPY package.json /app

COPY package-lock.json /app

RUN npm install

COPY . /app

RUN npm run build

FROM nginx:stable-alpine
COPY --from=react-build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/default.conf /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
COPY --from=react-build /app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 3500
CMD [ "nginx", "-g", "daemon off;" ]